CREATE TABLE IF NOT EXISTS tasks(
id INTEGER PRIMARY KEY AUTOINCREMENT,
description TEXT NOT NULL,
is_done BOOLEAN DEFAULT False,
time TEXT NOT NULL,
deadline TEXT NOT NULL,
user_id INTEGER,
FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
email TEXT UNIQUE,
password TEXT NOT NULL,
avatar BLOB DEFAULT NULL);